### PR TITLE
chore: added liveness probes to services which have healthcheck URLs

### PR DESCRIPTION
**Pull request by project-administrator**
Signed-off-by: Alex Renn <alexander.renn@securekey.com>

### CODE REVIEW

**Comment by rolsonquadras** [comment]
Can we update https://github.com/trustbloc/sandbox/blob/main/Makefile#L28 as well ?

**Comment by project-administrator** [comment]
> Can we update https://github.com/trustbloc/sandbox/blob/main/Makefile#L28 as well ?

done

**Review by rolsonquadras — APPROVED** [review]

**Comment by rolsonquadras** [comment]
> > Can we update https://github.com/trustbloc/sandbox/blob/main/Makefile#L28 as well ?
> 
> done

@project-administrator Sorry, I wasn't more specific ( I thought the similar PR in k8s was merged - https://github.com/trustbloc/k8s/pull/39). I merged it now. Can you please update it to latest version - https://github.com/trustbloc/k8s/commit/cc7728d94eef843bbb8f4c41b1e90e6db75884a3 ?

**Comment by project-administrator** [comment]
> > > Can we update https://github.com/trustbloc/sandbox/blob/main/Makefile#L28 as well ?
> > 
> > 
> > done
> 
> @project-administrator Sorry, I wasn't more specific ( I thought the similar PR in k8s was merged - [trustbloc/k8s#39](https://github.com/trustbloc/k8s/pull/39)). I merged it now. Can you please update it to latest version - [trustbloc/k8s@cc7728d](https://github.com/trustbloc/k8s/commit/cc7728d94eef843bbb8f4c41b1e90e6db75884a3) ?

done. 
But now UI-tests fail with the updated commit ID. 
The specified commit [trustbloc/k8s@cc7728d] also contains changes from another PR: https://github.com/trustbloc/k8s/pull/40. 
Tests have passed successfully before the PR#40: https://github.com/trustbloc/sandbox/actions/runs/850489693.
Need to investigate if it's the cause.

**Review by fqutishat — APPROVED** [review]

**Pull request merged**
