### PR TITLE
fix: rp-register-tenant job: patch only the last-created configmap

### PR DESCRIPTION
**Pull request by project-administrator**
Signed-off-by: Alex Renn <alexander.renn@securekey.com>

### CODE REVIEW

**Review by rolsonquadras — APPROVED** [review]

**Comment by alialkhalidi** [comment]
May be I'm missing something here, but wasn't the issue with the false assertion that a single configMap would the target for mutation? if so, the proposition was to get the target ```rp-env``` configMap from the running pod directly with something like:
```kubectl get pods -l 'component=rp,group=demo' -o jsonpath='{.items[*].spec.containers[0].envFrom[0].configMapRef.name}'```

**Review by alialkhalidi — COMMENTED** [review]
May be I'm missing something here, but wasn't the issue with the false assertion that a single configMap would the target for mutation? if so, the proposition was to get the target ```rp-env``` configMap from the running pod directly with something like:
```kubectl get pods -l 'component=rp,group=demo' -o jsonpath='{.items[*].spec.containers[0].envFrom[0].configMapRef.name}'```

**Comment by project-administrator** [comment]
> May be I'm missing something here, but wasn't the issue with the false assertion that a single configMap would the target for mutation? if so, the proposition was to get the target `rp-env` configMap from the running pod directly with something like:
> `kubectl get pods -l 'component=rp,group=demo' -o jsonpath='{.items[*].spec.containers[0].envFrom[0].configMapRef.name}'`

Why not mutate all found configmaps instead?

**Comment by alialkhalidi** [comment]
> > May be I'm missing something here, but wasn't the issue with the false assertion that a single configMap would the target for mutation? if so, the proposition was to get the target `rp-env` configMap from the running pod directly with something like:
> > `kubectl get pods -l 'component=rp,group=demo' -o jsonpath='{.items[*].spec.containers[0].envFrom[0].configMapRef.name}'`
> 
> We can do the `kubectl get pods -l 'component=rp,group=demo' -o jsonpath='{.items[*].spec.containers[0].envFrom[0].configMapRef.name}'` but imagine if there are multiple pods running with different configmaps (example -- during the rolling deployment)? We end up in the same situation when we get two configmaps returned. We can probably check whichever deployment is newer, but there is no guarantee that the rolling deployment succeeds if it's in progress.
> To me it seems more reliable (and straightforward) to mutate all available configmaps.


Well, if the "newest" rp rollout fails (a precondition to running this job), there is not much point for what this job is trying to do!!!! 
Additionally, mutating all configmap to the latest desired state renders rolling back logically incorrect; all previous versions of the rp deployment will have the nestest mutated config!!!

**Review by fqutishat — APPROVED** [review]

**Comment by project-administrator** [comment]
Good point. 
I made the change to process only the newest-created configmap instead of all found configmaps.

**Review by alialkhalidi — APPROVED** [review]

**Pull request merged**
