### PR TITLE
chore: update kubectl to match the kubernetes version

### PR DESCRIPTION
**Pull request by project-administrator**
Signed-off-by: Alex Renn <alexander.renn@securekey.com>

### CODE REVIEW

**Comment by soluchok** [comment]
@project-administrator This one also needs to be updated https://github.com/trustbloc/sandbox/blob/main/.github/workflows/ci.yml#L6

**Comment by project-administrator** [comment]
> @project-administrator This one also needs to be updated https://github.com/trustbloc/sandbox/blob/main/.github/workflows/ci.yml#L6

Done

**Review by soluchok — APPROVED** [review]

**Review by bstasyszyn — APPROVED** [review]

**Comment by rolsonquadras** [comment]
@project-administrator The related PR in k8s https://github.com/trustbloc/k8s/pull/64 is merged. Can you please update the k8s version in sandbox ?

**Comment by project-administrator** [comment]
> @project-administrator The related PR in k8s [trustbloc/k8s#64](https://github.com/trustbloc/k8s/pull/64) is merged. Can you please update the trustbloc/k8s version in sandbox ?

Done

**Pull request merged**
